spring.application.name=learn
spring.profiles.active=local

# Max file size (per file)
spring.servlet.multipart.max-file-size=10MB

# Max total request size
spring.servlet.multipart.max-request-size=10MB
aws.credentials.region=ap-south-1
aws.credentials.bucket=d4-s3-bucket

# MySQL properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# application.properties
# spring.devtools.restart.enabled=false
# spring.devtools.livereload.enabled=true